import os
from pathlib import Path
import matlab.engine
from tqdm import tqdm

def evaluate_windows_matlab(input_dir: str, output_dir: str, dpi: int = 300):
    """
    Evaluate MATLAB scripts on Windows local environment
    """
    input_path = Path(input_dir).resolve()
    output_path = Path(output_dir).resolve()
    output_path.mkdir(parents=True, exist_ok=True)

    m_files = list(input_path.glob("*.m"))
    total_scripts = len(m_files)

    if total_scripts == 0:
        print(f"No .m scripts found in '{input_dir}'.")
        return

    print("🚀 Starting Windows local MATLAB engine, please wait...")
    try:
        eng = matlab.engine.start_matlab()
    except Exception as e:
        print("❌ Failed to start local MATLAB engine! Please check if the Python version is compatible with the MATLAB version (recommended Python 3.10).")
        print(f"Error info: {e}")
        return

    print(f"🧪 Found {total_scripts} MATLAB scripts, starting Windows clean evaluation...\n")

    success_count = 0
    fail_count = 0
    error_details = []

    for m_file in tqdm(m_files, desc="MATLAB evaluation progress", unit="file"):
        script_name = m_file.stem
        output_image = output_path / f"{script_name}.png"
        

        input_dir_correct = str(input_path).replace('\\', '/')
        output_image_correct = str(output_image).replace('\\', '/')

        try:
            # 1. Environmental isolation: Erase the variables and windows from the previous round.
            eng.eval("close all; clearvars -except eng;", nargout=0)
            
            # 2. Switch to the folder where the script is located
            eng.cd(input_dir_correct, nargout=0)
            
            # 3. Run the .m script generated by the large model
            eng.eval(f"{script_name}", nargout=0)
            
            # 4. Force export the generated Figure as PNG at 300 DPI (exportgraphics will automatically crop the surrounding white space)
            matlab_export_cmd = f"if ~isempty(get(0, 'CurrentFigure')), exportgraphics(gcf, '{output_image_correct}', 'Resolution', {dpi}); end"
            eng.eval(matlab_export_cmd, nargout=0)
            
            # 5. Check the saved file status
            if output_image.exists():
                success_count += 1
            else:
                fail_count += 1
                error_details.append((m_file.name, "Script ran without errors, but no plot window was detected, and no image was generated."))
                
        except matlab.engine.MatlabExecutionError as e:
            fail_count += 1
            error_details.append((m_file.name, str(e).strip()))
        except Exception as e:
            fail_count += 1
            error_details.append((m_file.name, f"External call exception: {str(e)}"))

    eng.quit()

    # === Final evaluation statistics report ===
    actual_images = len(list(output_path.glob("*.png")))
    exec_success_rate = (success_count / total_scripts) * 100
    file_match_rate = (actual_images / total_scripts) * 100

    print("\n" + "="*60)
    print("📊 【FigCodeBench - Windows MATLAB Evaluation Report】")
    print("="*60)
    print(f"1. Original .m script count (expected):  {total_scripts} scripts")
    print(f"2. Successfully executed and generated images:    {success_count} scripts")
    print(f"3. Failed execution or no images generated:  {fail_count} scripts")
    print(f"4. Total images actually generated locally:  {actual_images} images")
    print("-" * 60)
    print(f"📈 Core metrics:")
    print(f"   - Code execution success rate: {exec_success_rate:.2f}%")
    print(f"   - File count consistency: {file_match_rate:.2f}% ({'✅ Fully consistent' if total_scripts == actual_images else '⚠️ Inconsistent count'})")
    print("="*60)



if __name__ == "__main__":
        
    models = ['internvl35-38B']
    sets = ['exemplary','user_generated']  
    
    
    tasks = ["Composition", "Geospatial", "Mathematical", "Statistical", "Temporal", "Relational"]
    
    for model in models:
            for s in sets:
                for task in tasks:
                                                    
                    SOURCE_M_DIR = f"xxxx\\results_final\\{model}\\Matlab\\{s}\\code_base\\{task}"
                    OUTPUT_IMG_DIR = f"xxxx\\results_final\\{model}\\Matlab\\{s}\\image_base\\{task}"

                    evaluate_windows_matlab(SOURCE_M_DIR, OUTPUT_IMG_DIR, dpi=300)
                
                
                for task in tasks:
                                    
                    SOURCE_M_DIR = f"xxxx\\results_final\\{model}\\Matlab\\{s}\\code_variant1\\{task}"
                    OUTPUT_IMG_DIR = f"xxxx\\results_final\\{model}\\Matlab\\{s}\\image_variant1\\{task}"

                    evaluate_windows_matlab(SOURCE_M_DIR, OUTPUT_IMG_DIR, dpi=300)
                    
                    
                for task in tasks:

                    SOURCE_M_DIR = f"xxxx\\results_final\\{model}\\Matlab\\{s}\\code_variant2\\{task}"
                    OUTPUT_IMG_DIR = f"xxxx\\results_final\\{model}\\Matlab\\{s}\\image_variant2\\{task}"

                    evaluate_windows_matlab(SOURCE_M_DIR, OUTPUT_IMG_DIR, dpi=300)